version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3340:3340'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f /fitness_app/tmp/pids/server.pid && yarn install --check-files && bundle exec rails s -p 3200 -b '0.0.0.0'"
    volumes:
      - .:/fitness_app
    ports:
      - "3200:3200"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql:
    driver: local